name: manifests
on: 
  pull_request:
    paths: 
      - 'b/**'
  push:
    paths: 
      - 'b/**'
jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls b/** | jq -R -s -c 'split("\n")[:-1]')"
  check:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      - run: |
          ./check-manifest ${{ martix.manifest }}
