on:
  push:
    paths:
      - 'b/**'
      - '.github/workflows/sample2.yml'
    

jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing shell script
        run: | 
          
          echo "::set-output name=matrix::{"include": [{"env": "xy"}, {"env": "yz"}]}"
            
