name: sample yaml
on:
  pull_request:
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    branches:
      - main
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-env-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: determine setup configuration
        id: setup-env-matrix-outputs-matrix
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git_diff=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})
          else
            git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi

          if [[ $(echo "git_diff" | grep 'b/') ]]; then
            deploy_git_diff=$(git diff --name-only origin${{ github.base_ref }} origin/${{ github.head_ref }} | grep 'b/')
          else
            deploy_git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'b/')

          echo "::set-output name=matrix::$(ls -d b/*/ | jq--raw-input --slurp --compact-output 'split("\n")[:-1]')"

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    env: 
      CUR_ENV: b/${{ matrix.env }}
    steps: 
      - uses: actions/checkout@v2
      - name: shell command
        run: |
          echo "${{ matrix.env }}"    

    
    
