name: manifests
on: 
  pull_request:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@3
      - run: python .github/shell/determinefolder.py
        
  
  
