name: sample yaml
on:
  pull_request:
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    branches:
      - main
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.job1.outputs.matrix }}
    steps:
      - id: filter
        with:
          filters: |
            paths: '!b/xz'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: determine setup configuration
        id: diff
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git_diff=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})
          else
            git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
          echo "::set-output name=matrix::[\"xy\", \"yz\"]"
      - name: check output(debug)
        run: |
          echo 'test ${{ fromJson(steps.job1.outputs.matrix) }}'
          echo '${{ fromJson(steps.job1.outputs.matrix) }}'

  build:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix: ${{ fromJson(needs.job1.outputs.matrix) }}
    env: 
      CUR_ENV: b/${{ matrix.env }}
    steps: 
      - uses: actions/checkout@v2
      - name: shell command
        run: |
          echo "${{ matrix.env }}"    

    
    
