name: sample yaml
on:
  pull_request:
    paths:
      - 'b/**'
  push:
    branches:
      - main
    paths:
      - 'b/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-env-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
