name: sample yaml
on:
  pull_request:
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    branches:
      - main
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-env-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: determine setup configuration
        id: diff
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git_diff=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})
          else
            git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi

          
      - name: setmatrix for build
        id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"env\":[{\"xy\"}, {"\yz\"}]}"    

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    env: 
      CUR_ENV: b/${{ matrix.env }}
    steps: 
      - uses: actions/checkout@v2
      - name: shell command
        run: |
          echo "${{ matrix.env }}"    

    
    
