name: sample yaml
on:
  pull_request:
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    branches:
      - main
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.job1.outputs.matrix }}
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: determine setup configuration
        id: diff
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git_diff=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})
          else
            git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi

          if [[ "$(echo "$git_diff" | grep 'b/')" ]]; then
             if ${{ github.event_name == 'pull_request' }}; then
               deploy_git_diff=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | 'b/**')
            else
               deploy_git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'b/**')
             fi   
