on:
  push:
    paths:
      - 'b/**'
      - '.github/workflows/sample2.yml'
    

jobs:
  buld:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: | 
          
          echo "::set-output name=matrix::{"include": [{"env": "xy"}, {"env": "yz"}]}"
          
            
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    env:
      CUR_ENV: ${{ matrix.env }}
    steps:
      - run: |
          echo "${{ matrix.env }}"    
