name: manifests
on: 
  pull_request:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls b/** | jq -R -s -c 'split("\n")[:-1]')"
        
  
  build:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(needs.list-manifests.output.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ matrix.env }}"    
