name: manifests
on: 
  pull_request:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
      - '.github/shell/determinefolder.py'
  push:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
      - '.github/shell/determinefolder.py'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-env-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: determine setup configuration
        id: setup-env-matrix
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git_diff=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }})
          else
            git_diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi

          if [[ $(echo "git_diff" | grep 'b/') ]]; then
            if ${{ github.event_name == 'pull_request' }}; then
              b=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep '**')
            else
              b=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '**')
            fi  
          
              echo ::set-output name=matrix::$(python .github/shell/determinefolder.py "$b")
              echo "$matrix"
          fi 
      - name: check output (Debug)
        run: |
          echo '${{ fromJson(steps.setup-env-matrix.outputs.matrix) }}' 
          echo "hello world"
          
