name: manifests
on: 
  pull_request:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
      
  push:
    paths: 
      - 'b/**'
      - '.github/workflows/sample.yml'
      
jobs:
  env-config-diff:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.env-config-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          a= 1
          echo "$a"

          
