name: sample yaml
on:
  pull_request:
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
  push:
    branches:
      - main
    paths:
      - 'b/**'
      - '.github/workflows/sample.yml'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.job1.outputs.matrix }}
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: determine setup configuration
        id: diff
        run: |
           export DIFF=$( git diff --dirstat=files,0,cumulative ${{ github.event.pull_request.base.sha }} | awk -F ' ' '{print $2}' )
           echo "$DIFF"
          

