name: Run Script

on: push
  
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            exclude_directories = set(['ab', 'zx'])

            for dname, dirs,files in os.walk('./b'):
               dirs[:] = [d for d in dirs if d not in exclude_directories]
               print(dirs)
