name: Run Script

on: push
  
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            for root, dirs, files in os.walk("."):
               if "b" in dirs:
                 dirs.remove("b/ab")
               for file in files:
                 print(f"Dealing with file {dirs}/{file}")
