name: Run Script

on: push
  
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import json
            import re
            import sys
            def main():
               if len(sys.argv) < 2:
               print("Path to file containing modified paths is required.")
               exit(1)
               with open(sys.argv[1]) as input_file:
               modified_files = input_file.read()
            if __name__ == __"main":
              main
            
            #b = []
            #exclude_directories = set(['ab', 'zx'])

            #for dname, dirs,files in os.walk('./b'):
               #dirs[:] = [d for d in dirs if d not in exclude_directories]
                  
