on: push
jobs:
  build:
    runson-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        run: |
          python .github/shell/determineenv.py
        
          - 
        
    
