name: Run Script

on: push
  
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import json
            import re
            import sys
            list1 = os.listdir()
            for filename is list1:
            r=open(filename,"r")
            
            #b = []
            #exclude_directories = set(['ab', 'zx'])

            #for dname, dirs,files in os.walk('./b'):
               #dirs[:] = [d for d in dirs if d not in exclude_directories]
                  
